language: php

php:
    - 8.0
    - 8.1

install:
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/parallel-lint src tests
    - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src tests
    - vendor/bin/tester -p php tests/ -s -c tests/php.ini